json.id @user.id
json.username @user.username
json.location @user.location
json.summary @user.summary
json.image_url @user.image_url
json.gender @user.gender
json.eating_speed @user.eating_speed
json.age @user.age
json.five_foods @user.five_foods
json.three_faves @user.three_faves
json.daytime @user.daytime
json.hobbies @user.hobbies
json.friday @user.friday
json.message_if @user.message_if
